### PR TITLE
get rid of generated runner. introduced c7n_test

### PR DESCRIPTION
**Pull request by beginningineer**

### CODE REVIEW

**Comment by alexkarpitski** [comment]
Looks good.
NB _test_iam_ fails in both versions for me.

**Comment by alexkarpitski** [comment]
Looks like we can also get rid of these in _WORKSPACE_:
```
local_repository(
    name = "c7n",
    path = "c7n",
)

local_repository(
    name = "c7n_gcp",
    path = "tools/c7n_gcp/c7n_gcp",
)
```

**Comment by alexkarpitski** [comment]
> Looks like we can also get rid of these in _WORKSPACE_:
> 
> ```
> local_repository(
>     name = "c7n",
>     path = "c7n",
> )
> 
> local_repository(
>     name = "c7n_gcp",
>     path = "tools/c7n_gcp/c7n_gcp",
> )
> ```

Removed in #6.

**Comment by beginningineer** [comment]
> Looks good.
> NB _test_iam_ fails in either version for me.

look like concrete test case (test_credential_access_key_multifilter_delete) is failing even in upstream master branch

**Pull request merged**
